# Generated by Django 5.2.11 on 2026-02-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sycoatimetable',
            name='batch',
            field=models.CharField(default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='sycobtimetable',
            name='batch',
            field=models.CharField(default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='tycoatimetable',
            name='batch',
            field=models.CharField(default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='tycobtimetable',
            name='batch',
            field=models.CharField(default='ALL', max_length=10),
        ),
    ]
