# Generated by Django 5.2.11 on 2026-02-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_timetable', '0002_sycoatimetable_batch_sycobtimetable_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sycoainput',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='sycoainput',
            name='lab_duration',
        ),
        migrations.RemoveField(
            model_name='sycoainput',
            name='weekly_lecture_count',
        ),
        migrations.RemoveField(
            model_name='sycobinput',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='sycobinput',
            name='lab_duration',
        ),
        migrations.RemoveField(
            model_name='sycobinput',
            name='weekly_lecture_count',
        ),
        migrations.RemoveField(
            model_name='tycoainput',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='tycoainput',
            name='lab_duration',
        ),
        migrations.RemoveField(
            model_name='tycoainput',
            name='weekly_lecture_count',
        ),
        migrations.RemoveField(
            model_name='tycobinput',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='tycobinput',
            name='lab_duration',
        ),
        migrations.RemoveField(
            model_name='tycobinput',
            name='weekly_lecture_count',
        ),
        migrations.AddField(
            model_name='sycoainput',
            name='practical_credits',
            field=models.IntegerField(default=0, help_text='Practical Load (2 credits = 1 block of 2 hours)'),
        ),
        migrations.AddField(
            model_name='sycoainput',
            name='theory_credits',
            field=models.IntegerField(default=0, help_text='Theory Load (e.g. 5 means 5 hours/week)'),
        ),
        migrations.AddField(
            model_name='sycobinput',
            name='practical_credits',
            field=models.IntegerField(default=0, help_text='Practical Load (2 credits = 1 block of 2 hours)'),
        ),
        migrations.AddField(
            model_name='sycobinput',
            name='theory_credits',
            field=models.IntegerField(default=0, help_text='Theory Load (e.g. 5 means 5 hours/week)'),
        ),
        migrations.AddField(
            model_name='tycoainput',
            name='practical_credits',
            field=models.IntegerField(default=0, help_text='Practical Load (2 credits = 1 block of 2 hours)'),
        ),
        migrations.AddField(
            model_name='tycoainput',
            name='theory_credits',
            field=models.IntegerField(default=0, help_text='Theory Load (e.g. 5 means 5 hours/week)'),
        ),
        migrations.AddField(
            model_name='tycobinput',
            name='practical_credits',
            field=models.IntegerField(default=0, help_text='Practical Load (2 credits = 1 block of 2 hours)'),
        ),
        migrations.AddField(
            model_name='tycobinput',
            name='theory_credits',
            field=models.IntegerField(default=0, help_text='Theory Load (e.g. 5 means 5 hours/week)'),
        ),
    ]
