# Generated by Django 5.2.7 on 2026-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_timetable', '0004_fycoinput_fycotimetable_sycoinput_sycotimetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('tyco', 'TYCO'), ('syco', 'SYCO'), ('fyco', 'FYCO')], max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('theory_credits', models.IntegerField(default=0)),
                ('practical_credits', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['class_name', 'subject_name'],
                'unique_together': {('class_name', 'subject_name')},
            },
        ),
    ]
