# Generated by Django 5.2.7 on 2026-03-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_timetable', '0005_mastersubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersubject',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='e.g. OSY, STE. Auto-used in timetable output if provided.', max_length=10, null=True),
        ),
    ]
