# Generated by Django 5.2.7 on 2026-03-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_timetable', '0006_mastersubject_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FycoBInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('theory_credits', models.IntegerField(default=0, help_text='Theory Load (e.g. 5 means 5 hours/week)')),
                ('practical_credits', models.IntegerField(default=0, help_text='Practical Load (2 credits = 1 block of 2 hours)')),
                ('time_constraints', models.TextField(blank=True, help_text='JSON or text description of constraints', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FycoBTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(default='ALL', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SycoBInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('theory_credits', models.IntegerField(default=0, help_text='Theory Load (e.g. 5 means 5 hours/week)')),
                ('practical_credits', models.IntegerField(default=0, help_text='Practical Load (2 credits = 1 block of 2 hours)')),
                ('time_constraints', models.TextField(blank=True, help_text='JSON or text description of constraints', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SycoBTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(default='ALL', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TycoBInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('theory_credits', models.IntegerField(default=0, help_text='Theory Load (e.g. 5 means 5 hours/week)')),
                ('practical_credits', models.IntegerField(default=0, help_text='Practical Load (2 credits = 1 block of 2 hours)')),
                ('time_constraints', models.TextField(blank=True, help_text='JSON or text description of constraints', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TycoBTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(default='ALL', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mastersubject',
            name='class_name',
            field=models.CharField(choices=[('tyco', 'TYCO A'), ('tyco_b', 'TYCO B'), ('syco', 'SYCO A'), ('syco_b', 'SYCO B'), ('fyco', 'FYCO A'), ('fyco_b', 'FYCO B')], max_length=10),
        ),
    ]
